name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Vulkan SDK - edvn0          
      uses: edvn0/setup-vulkan-sdk@v1.3.0
      with:
       vulkan-query-version: 1.3.224.1
       vulkan-components: Vulkan-Headers, Vulkan-Loader
       vulkan-use-cache: true
    - name: Run tests
      run: cargo test --workspace
